apiVersion: v1
kind: Namespace
metadata:
  name: prod-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verademo
  namespace: prod-env
  labels:
    app: verademo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verademo
  template:
    metadata:
      labels:
        app: verademo
    spec:
      containers:
      - name: verademo
        image: mfldosari/verademo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: verademo-service
  namespace: prod-env
spec:
  type: NodePort
  selector:
    app: verademo
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30100
