name: Build Superset Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Build Docker image and load to Docker daemon
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: verademo:dev
          outputs: type=docker,dest=/tmp/image.tar
          load: true 
          # -----------------------------------------------------------------

      # You can now save the image as a tarball, as it is loaded locally
      - name: Save image as tarball
        run: docker save verademo:dev -o verademo-dev.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: verademo-image
          path: verademo-dev.tar 
